name: Build Android APK

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4

    - name: Move files to root if nested
      run: |
        if [ -d "ruhul-media.app" ]; then
          shopt -s dotglob
          mv ruhul-media.app/* .
          rmdir ruhul-media.app
          shopt -u dotglob
        fi

    - name: set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'

    - name: Setup Gradle
      uses: gradle/actions/setup-gradle@v3

    - name: Build with Gradle
      run: gradle assembleDebug

    - name: Upload APK
      uses: actions/upload-artifact@v4
      with:
        name: app-debug
        path: '**/build/outputs/apk/debug/app-debug.apk'
